config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "welcome#index"

  resources :orders, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  
  validates :username, presence: true
  validates :amount, numericality: { greater_than: 0 }
  validates :order_no, uniqueness: true 
  
  before_validation :build_order_no, on: :create

  enum pay_type: {
    "ATM": "A",
    "Credit Card": "C"
  }
  
  private 
  def build_order_no
    now = Date.current
    self.order_no = "RB#{now.strftime('%Y%m%d')}#{[*'A'..'Z', *'0'..'9'].sample(10).join}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @order = current_user.orders.new
  end

  def create
    @order = current_user.orders.new(order_params)
    if @order.save
      gateway = Sinopac::FunBiz::Gateway.new
      order = Sinopac::FunBiz::Order.new(
        order_no: @order.order_no,
        amount: @order.amount,
        product_name: 'test'
      )
      result = gateway.pay!(order: order, pay_type: :credit_card)
      if result.success?
        redirect_to result.payment_url
      else
        rediect_to root_path, notice: 'There is some errors occurred.'
      end
    else
      render :new, flash_now: "There are some errors occured!"
    end
  end

  private
  def order_params
    params.require(:order).permit(:username, :amount, :memo, :pay_type)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper  
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Donate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'shared/navbar' %>
    <div class="container mt-3">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/orders/new.html.erb
<div class="row justify-content-center">
  <div class="col-md-8 col-10">
    <%= form_with model: @order do |f| %>
      <div class="mb-3 form-field">
        <%= f.label :username, "Name", class: "form-label fw-bold" %>
        <%= f.text_field :username, autofocus: true, class: "form-control" %>
      </div>   
      
      <div class="mb-3 form-field">
        <%= f.label :amount, "Amount", class: "form-label fw-bold" %>
        <%= f.number_field :amount, value: 100, min: 10, class: "form-control" %>
      </div>

      <div class="mb-3 form-field">
        <%= f.label :memo, "Memo", class: "form-label fw-bold" %>
        <%= f.text_area :memo, rows: 5, class: "form-control" %>
      </div>

      <div class="mb-3 form-field">
        <%= f.label :pay_type, "Pay", class: "form-label fw-bold" %>
        <%= f.select :pay_type, Order.pay_types %>
      </div>

      <div class="mb-3 form-field">
        <%= f.submit "Pay!", class: "btn btn-danger fw-bold" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-<%= flash_class(key) %> alert-dismissible fade show" role="alert">
      <strong><%= value %></strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3 bg-light">
  <div class="container text-center">
    Copyright © 2021 <%= link_to "Donate Me", root_path, class: "text-decoration-none text-dark fw-bold" %>
    Design by <%= link_to "K. Cheng", 'https://github.com/kaycheng', class: "text-decoration-none text-dark fw-bold", target: "_blank" %>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm p-2 mb-3 bg-body">
  <div class="container-fluid">
    <%= link_to "Donate Me", root_path, class: "navbar-brand fw-bolder text-decoration-none fs-3" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if current_user && user_signed_in? %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link active fw-bold" %> 
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link active fw-bold" %>
          </li> 
        
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link active fw-bold" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<h1 class="heading">Have you prepared money?</h1>
<h2 class="subtitle">It's time to add value to faith.</h2>

<%= link_to new_order_path, class: "btn btn-danger fw-bold" do %>
  Deposite &nbsp; <i class="ml-2 fas fa-money-check-alt"></i>
<% end %>

<%= link_to "About Us", "#", class: "btn btn-outline-danger fw-bold" %>